export extern let a: int;
extern let b: int;
export let c: int = 10;
let x: bool;
let y: int = 40;
let z = false;
let mutable w = 10.15;
let (x, y) = (1, 20);
let (x,) = (4,);
let (mutable y,): (bool,) = (false,);
let (mutable y, z): (bool, int) = (false, 389);
