# Need python to use the build process
language: python
python:
  - "3.4"

# Install any testing or build dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get install -y libboost-all-dev
  - sudo sh -c 'echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main\ndeb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main\ndeb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main\ndeb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" >> /etc/apt/sources.list'
  - sudo apt-get update
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get install clang-3.5 clang-3.5-doc libclang-common-3.5-dev libclang-3.5-dev libclang1-3.5 libclang1-3.5-dbg libllvm-3.5-ocaml-dev libllvm3.5 libllvm3.5-dbg lldb-3.5 llvm-3.5 llvm-3.5-dev llvm-3.5-doc llvm-3.5-examples llvm-3.5-runtime clang-modernize-3.5 clang-format-3.5 python-clang-3.5 lldb-3.5-dev

# Command to build project
before_script: ./waf configure --check-cxx-compiler="clang++" build

# Command to run tests
script: ./waf test
