# Need python to use the build process
language: python
python:
  - "3.4"

# Install any testing or build dependencies
install:
  - sudo apt-get install -y llvm-dev libboost-all-dev clang
  - pip install -r requirements.txt

# Command to build project
before_script: ./waf configure --check-cxx-compiler="clang++" build

# Command to run tests
script: ./waf test
