# Need python to use the build process
language: python
python:
  - "3.4"

# Install any testing or build dependencies
install:
  - pip install -r requirements.txt
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get install -y libboost1.55-all-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo sh -c 'echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main\ndeb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main\ndeb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main\ndeb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" >> /etc/apt/sources.list'
  - sudo apt-get update
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get install -y --force-yes clang-3.5 llvm-3.5-dev

# Command to build project
before_script: ./waf configure --check-cxx-compiler="clang++" build

# Command to run tests
script: ./waf test
