#!/usr/bin/env bash

# Resolve base directory
DIR=$(readlink -f -- $(dirname $0)/..)

# Resolve llvm-config
LLVM_CONFIG=$(ls /usr/bin/llvm-config* | sort -r | head -n1)

# Build
(cd $DIR; ./waf configure --with-llvm-config=$LLVM_CONFIG build -p)
